[package]
name = "kirigami-targets"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
three-d-animation.workspace = true
three-d-core.workspace = true
three-d-formats.workspace = true
