name: Validate

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --locked --workspace --all-targets -- -D warnings
      - name: Tests
        run: cargo test --locked --workspace --all-targets
      - name: WASM compile
        run: cargo build --locked -p kirigami-wasm --target wasm32-unknown-unknown --release
