name: Validate

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: wasm32-unknown-unknown
      - name: Formatting
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --locked --workspace --all-targets -- -D warnings
      - name: Tests
        run: cargo test --locked --workspace --all-targets
      - name: WASM compile
        run: cargo build --locked -p kirigami-wasm --target wasm32-unknown-unknown --release
